version: '3.9'

services:
  app-server:
    container_name: app
    image: app
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env.example
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - database
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      PORT: ${PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: postgresql://
    restart: always
    command: npm run start:dev

  database:
    container_name: database
    image: postgres
    build:
      context: .
      dockerfile: ./database/Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pglogs:/var/log/postgresql/postgresql.log
networks:
  default:
    driver: bridge
volumes:
  pgdata:
  pglogs:
